### ISSUE TITLE
ID3 implementation.

### ISSUE THREAD

**Issue by subhajit26** [Alihaider122/ID3-Decision-Tree-Implemented-in-python#1]
Hi,
       Can you please give the code section for prediction in ID3 algorithm based on this pseudocode.

predict( node, x)
    if node is leaf
        return the class label of node
    else
        find the child c among the children of node 
             representing the value that x has for 
             the split_attribute of node
        return predict( c, x)

**Comment by ialihaider75** [comment]
Already implemented in this code kindly look closely you will find what you want in this code. thanks
